specifications/09-strategy-constraints.json

Statically typed clients have no way of implementing custom properties
at the top level of the context object. A better solution here is to use
the 'properties' sub-property as recommended by the documentation.

Put custom context properties under 'properties'

---

specifications/08-variants.json

The implementation differs here between clients. Before I make the changes to those that return an enabled variant in this case I wanted to check if this is a correct understanding on what should happen.

Disabled toggles should produce a disabled variant

---

specifications/12-custom-stickiness.json
specifications/index.json

feat: add specifications for custom stickiness

---

README.md

Pardon if it's legitimate, just did diagonal reading and noticed the typo (and `u` and `i` are close on the qwerty keyboard).

Fix api typo

---

README.md
specifications/13-constraint-operators.json

Makes the name of `13-constraint-operators` consistent with other spec names.

fix: remove .json suffix from spec name

---

index.js

The validation tests don't actually fail correctly when validation picks up and error. This sets the exit code to a non zero value so that tests will actually fail

fix: make tests actually fail when validation of schema fails

---

schema/context-schema.js
specifications/13-constraint-operators.json

We saw some inconsistent handling of missing context fields on in the SDK together with `IN` and `NOT_IN` operator. 
E.g. When the user has a `NOT_IN` and does not provide any context field the SDK should return true, while the node SDK is currently always returning false in that case (fixed via https://github.com/Unleash/unleash-client-node/pull/340)

fix: add cases for missing contextFields together with IN

---

specifications/15-global-constraints.json

This PR fixes a broken specification test where the segment was supposed to be missing, but in reality it was defined, resulting in a broken test.

fix: set segment id to 404

---

specifications/08-variants.json

When variants are empty, even if the feature toggle is enabled we expect the SDK to respond with the default variant (which unless overridden should be false)
Examples of the behavior can be found in:
- Node SDK: https://github.com/Unleash/unleash-client-node/blob/c031cd70279ede90ead1839fdc8537eca9187713/src/client.ts#L157-L164 
- Go SDK: https://github.com/Unleash/unleash-client-go/blob/ebfcf13a52ddbfcb6c4fe96afb4b713acad25739/client.go#L368-L370  and [default variant disabled](https://github.com/Unleash/unleash-client-go/blob/3c2306073d115829dc8943877f109c48da689169/api/variant.go#L78-L80)
- Java SDK test: https://github.com/Unleash/unleash-client-java/blob/be22d603ae9a37cb0617e6ac3397e823c244f9fa/src/test/java/io/getunleash/variant/VariantUtilTest.java#L41-L49 
- Python SDK test: …

If variants are empty we expect FT to be disabled

---

specifications/13-constraint-operators.json

The strEndsWith test case was previously checking that @some-email.com ends with @some-email.com. This means that an incorrectly implemented SDK could check that the context property ended with the constraint property and still pass the specifications. 
This patches that behaviour, meaning that dependent SDKs will now fail that test case correctly if the implementation is incorrect.

fix: this patches the strEndsWith test case

---

specifications/16-strategy-variants.json

Seems we have a duplicate property variants property in the variant strategy tests, this removes that

fix: trim duplicate variant strategy property

---

specifications/08-variants.json

SDKs should provide a disabled variant when the rollout percentage is set to 0%. This adjustment is being implemented to address an issue with the PHP SDK. Currently, the PHP SDK returns a variant even when a feature is disabled by a strategy.

feat: add empty variant test when strategy does not match/feature is disabled

---

package.json
schema/features-schema.js
specifications/17-dependent-features.json
specifications/index.json

**Spec for dependent features**
Data structure for dependent features:
* depend on parent being enabled: `{feature: 'parent'}`
* depend on parent being disabled (useful for kill-switches): `{feature: 'parent', enabled: false}`
* depend on parent resolving to a value/variant: `{feature: 'parent', variants: ['parentVariant', 'anotherParentVariant']}`
We're deliberately choosing `feature` as a key to have an option for other types of dependencies e.g. strategies
Most of the code has the same activation strategy with a strategy variant. Enabled tests and variant tests are almost identical (only description and expected result are different).
Interesting cases:
* you can depend on many features (with AND operator between them)
* when you depend on a parent feature variant you can specify a …

feat: dependent features

---

specifications/17-dependent-features.json

This change adds a new test case to the dependent features spec:
If a child depends on a parent's variant, but expects that variant to
be "disabled", the child should nonetheless be disabled if the parent
is disabled.
In other words, the only way for that to be true is if the parent has
a named variant called "disabled".
This covers a hole in the spec where a child could be enabled even if
its parent was disabled, as long as the child depended on the parent's
"disabled" variant.

fix: add test case for dependency asking for disabled variant

---

schema/test-case-schema.js
specifications/08-variants.json
specifications/12-custom-stickiness.json
specifications/16-strategy-variants.json
specifications/17-dependent-features.json

Added `feature_enabled` property in Variant to indicate feature toggle status independent of variant presence.
Related to https://github.com/Unleash/unleash-client-python/issues/284
Internal ticket: [issue/SR-151/update-client-spec-to-include-feature-enabled-property-in-variant](https://linear.app/unleash/issue/SR-151/update-client-spec-to-include-feature-enabled-property-in-variant)
Before this change, clients had to check if variants existed for a specific feature or use a combination of get_variant() and is_enabled() calls, which could lead to inaccurate metrics. This change allows for a single method call that provides complete information about the feature's enablement and associated variant.

feat: add `feature_enabled` property to variants

---

specifications/13-constraint-operators.json

Related to https://github.com/Unleash/client-specification/issues/77
Tested that this works in Node SDK, but not in .NET SDK.

fix: add case for inverted IN and NOT_IN

---

package.json
specifications/16-strategy-variants.json

Adding missing scenario where:
* stickiness is non default
* stickiness is available on strategy with variants
* stickiness is not available on variants themselves
This matches the data we get from edge.
What I don't want to specify and I deliberately omit is when variant on strategy and on strategy variant differ. This situation should not be possible. 
The values that I chose for test (clientId="1" and clientId="2") show the bug in the node SDK.

test: add missing test for custom stickiness only on strategy with variants

---

specifications/13-constraint-operators.json

We saw with the Java SDK that we had a mismatch when startsWith was case insensitive. This test will fail with Java SDK <9.2.1

task: add test case for case insensitive starts with

---

specifications/15-global-constraints.json

This test adds variants to an existing feature and expects them to work well in the presence of segments.
This covers the case reported here: https://github.com/Unleash/unleash-client-ruby/pull/194 (tested locally). 
Also, validated that the current unleash-client-node spec tests succeeds for this new scenario.

chore: combine a variant test with a segment contraint

---

specifications/18-utf8-flag-names.json
specifications/index.json

https://linear.app/unleash/issue/2-3110/net-sdk-utf-8-scandinavian-character-issue
Adding a new test for flag names with valid UTF-8 characters.

chore: add UTF-8 flag names test
